apiVersion: v1
kind: Secret
metadata:
  name: special-secret-v2
stringData:
  cert: certificate-value
  password: password-value
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-envfrom
spec:
  containers:
    - name: container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: special-secret-v2
  restartPolicy: Never