apiVersion: v1
kind: Secret
metadata:
  name: special-config-v2
stringData:
  cert: certificate-value
  password: password-value
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-envfrom
spec:
  containers:
    - name: container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config-v2
  restartPolicy: Never