apiVersion: v1
kind: Secret
metadata:
  name: special-secret-v1
stringData:
  cert: certificate-value
  password: password-value
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-env
spec:
  containers:
    - name: container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo $(PASSWORD)" ]
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: special-secret-v1
              key: password
  restartPolicy: Never