# docker run -d \
#   --net=host \
#   --privileged \
#   --name nfs-server \
#   -v /exports:/exports \
#   sbeliakou/nfs-server \
#     /exports

apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind-tcp
      port: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      protocol: UDP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nfs-server
subsets:
  - addresses:
      - ip: 192.168.56.225
    ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind-tcp
      port: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      protocol: UDP
