apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: nfs
      mountPath: "/usr/share/nginx/html/"
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
    securityContext:
      privileged: true
  volumes:
  - name: nfs
    nfs:
      # server: nfs-server.default.svc.cluster.local
      server: nfs-server
      path: "/exports"
      readOnly: false