apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-pvc-001
spec:
  containers:
  - name: container
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
      - name: persistent-storage
        mountPath: /data
    securityContext:
          privileged: true
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: nfs-storage-001-pvc