# Volumes shared between Containers within a Pod

apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-emptydir
spec:
  initContainers:
  - name: constainer-init
    image: busybox
    command: ["touch", "/shared-dir/file-1", "/shared-dir-memory/file-2"]
    volumeMounts:
    - name: pod-shared-volume
      mountPath: /shared-dir
    - name: pod-shared-volume-memory
      mountPath: /shared-dir-memory  
  containers:
  - name: container-1
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
    - name: pod-shared-volume
      mountPath: /shared-dir
    - name: pod-shared-volume-memory
      mountPath: /shared-dir-memory
  - name: container-2
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
    - name: pod-shared-volume
      mountPath: /shared-dir
    - name: pod-shared-volume-memory
      mountPath: /shared-dir-memory
  volumes:
  - name: pod-shared-volume
    emptyDir: {}
  - name: pod-shared-volume-memory
    emptyDir:
      medium: Memory